//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CM_HINMOI_ALL
    {
        public string ITM_CD { get; set; }
        public System.DateTime START_TS { get; set; }
        public string CO_CD { get; set; }
        public string EDITION_NO { get; set; }
        public string EDITION_REMARK { get; set; }
        public string DRAWING_BOARD { get; set; }
        public string DRAWING_B_REV { get; set; }
        public string DRAWING_B_ITEM_NO { get; set; }
        public string SPECIFICATIONS { get; set; }
        public string SPECIFICATIONS_REV { get; set; }
        public string D_B_FILE_PATH { get; set; }
        public string SPEC_FILE_PATH { get; set; }
        public string SUB_CHAR1 { get; set; }
        public string SUB_CHAR2 { get; set; }
        public string SUB_CHAR3 { get; set; }
        public string SUB_CHAR4 { get; set; }
        public string SUB_CHAR5 { get; set; }
        public Nullable<decimal> SUB_NUM1 { get; set; }
        public Nullable<decimal> SUB_NUM2 { get; set; }
        public Nullable<decimal> SUB_NUM3 { get; set; }
        public Nullable<decimal> SUB_NUM4 { get; set; }
        public Nullable<decimal> SUB_NUM5 { get; set; }
        public Nullable<decimal> SUB_NUM6 { get; set; }
        public Nullable<decimal> SUB_NUM7 { get; set; }
        public Nullable<decimal> SUB_NUM8 { get; set; }
        public Nullable<decimal> SUB_NUM9 { get; set; }
        public Nullable<decimal> SUB_NUM10 { get; set; }
        public string REMARK { get; set; }
        public System.DateTime END_TS { get; set; }
        public Nullable<System.DateTime> INS_TS { get; set; }
        public string INS_USR_ID { get; set; }
        public int UPD_CNTR { get; set; }
        public Nullable<System.DateTime> UPD_TS { get; set; }
        public string UPD_USR_ID { get; set; }
    }
}
