//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CM_HINMO_ALL
    {
        public string ITM_CD { get; set; }
        public string CO_CD { get; set; }
        public string ITM_NM { get; set; }
        public string ITM_ABBR { get; set; }
        public string ITM_TYP { get; set; }
        public string PH_ITM_TYP { get; set; }
        public string NON_MRP_FLG { get; set; }
        public string UNIT_CD { get; set; }
        public decimal PCKG_UNIT_QTY { get; set; }
        public string PCKG_UNIT_CD { get; set; }
        public string MAIN_INP_CD { get; set; }
        public string SCH_FLG { get; set; }
        public string ITM_ATT_TYP { get; set; }
        public string INPT_ALLOC_FLG { get; set; }
        public string SO_ALLOC_FLG { get; set; }
        public string VMI_FLG { get; set; }
        public Nullable<decimal> REQ_RSTR_QTY { get; set; }
        public string FIL_BAK_FLG { get; set; }
        public Nullable<int> XFR_MRG_LT { get; set; }
        public string XFR_MRG_LT_UNIT { get; set; }
        public Nullable<decimal> TRNSFR_LOT_UNIT_QTY { get; set; }
        public string PROD_ITM_GRP_CD { get; set; }
        public string AC_ITM_GRP_CD { get; set; }
        public string ITM_JNL_CD { get; set; }
        public string HS_CD { get; set; }
        public string INO_PTN_CD { get; set; }
        public string LOT_NO_INO_TYP { get; set; }
        public string APS_TGT_FLG { get; set; }
        public string EXT_ITM_NM { get; set; }
        public string PTN_CD { get; set; }
        public string JAN_CD { get; set; }
        public string SLS_ARRG_TYP { get; set; }
        public string DSH_TYP { get; set; }
        public decimal PKNG_QTY { get; set; }
        public string SLS_CTAX_CD { get; set; }
        public string NEW_SLS_CTAX_CD { get; set; }
        public Nullable<System.DateTime> NEW_SLS_CTAX_CD_ST_DT { get; set; }
        public string PURC_CTAX_CD { get; set; }
        public string NEW_PURC_CTAX_CD { get; set; }
        public Nullable<System.DateTime> NEW_PURC_CTAX_CD_ST_DT { get; set; }
        public string SLS_APP_TMG_TYP { get; set; }
        public string SPC_RESP_FLG { get; set; }
        public string SLS_ACT_XTR_FLG { get; set; }
        public string MINUS_UPRI_PRM_FLG { get; set; }
        public string SUNDRY_FLG { get; set; }
        public string PLN_PLN_TYP { get; set; }
        public Nullable<decimal> COST_STD_QTY { get; set; }
        public string ITM_CP_CD { get; set; }
        public string EACH_TIME_ITM_FLG { get; set; }
        public string QTN_SNO_NESS { get; set; }
        public string SLO_SNO_NESS { get; set; }
        public string DEF_PURC_UNIT_CD { get; set; }
        public string DEF_SHIP_UNIT_CD { get; set; }
        public string UPRI_CHG_AVL_FLG { get; set; }
        public Nullable<short> EXPR_DAYS { get; set; }
        public Nullable<short> GUARANTEE_MTHS { get; set; }
        public string BOM_SEIBAN_TYP { get; set; }
        public string BOM_SUB_SEIBAN_TYP { get; set; }
        public string CTG_A { get; set; }
        public string CTG_B { get; set; }
        public string CTG_C { get; set; }
        public string CTG_D { get; set; }
        public string CTG_E { get; set; }
        public string CTG_F { get; set; }
        public string CTG_G { get; set; }
        public string CTG_H { get; set; }
        public string CTG_I { get; set; }
        public string CTG_J { get; set; }
        public string SLO_STOP_FLG { get; set; }
        public Nullable<System.DateTime> SLO_STOP_DT { get; set; }
        public string PO_STOP_FLG { get; set; }
        public Nullable<System.DateTime> PO_STOP_DT { get; set; }
        public string INST_STOP_FLG { get; set; }
        public Nullable<System.DateTime> INST_STOP_DT { get; set; }
        public string SPE_NOTE { get; set; }
        public string PURC_TGT_FLG { get; set; }
        public string PURC_STNG_COMPL_FLG { get; set; }
        public string PROD_TGT_FLG { get; set; }
        public string PROD_STNG_COMPL_FLG { get; set; }
        public string INSP_TGT_FLG { get; set; }
        public string INSP_STNG_COMPL_FLG { get; set; }
        public string SLS_TGT_FLG { get; set; }
        public string SLS_STNG_COMPL_FLG { get; set; }
        public string INVALID_FLG { get; set; }
        public string NOTE { get; set; }
        public string DEFAULT_FLG { get; set; }
        public Nullable<short> DEADLINE_DAYS { get; set; }
        public string PO_BASE_DATE { get; set; }
        public Nullable<System.DateTime> INS_TS { get; set; }
        public string INS_USR_ID { get; set; }
        public int UPD_CNTR { get; set; }
        public Nullable<System.DateTime> UPD_TS { get; set; }
        public string UPD_USR_ID { get; set; }
    }
}
