//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CM_ITM_UNIT_ALL
    {
        public string ITM_CD { get; set; }
        public string UNIT_CD { get; set; }
        public string CO_CD { get; set; }
        public decimal UNIT_CONV_QTY { get; set; }
        public Nullable<decimal> UNIT_WT { get; set; }
        public Nullable<decimal> UNIT_DIM { get; set; }
        public string INVALID_FLG { get; set; }
        public string NOTE { get; set; }
        public Nullable<System.DateTime> INS_TS { get; set; }
        public string INS_USR_ID { get; set; }
        public int UPD_CNTR { get; set; }
        public Nullable<System.DateTime> UPD_TS { get; set; }
        public string UPD_USR_ID { get; set; }
    }
}
