//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CM_NOUHIN_ALL
    {
        public string SCST_CD { get; set; }
        public string CO_CD { get; set; }
        public string SCST_NM { get; set; }
        public string DPT_NM { get; set; }
        public string USR_NM { get; set; }
        public string CST_CD { get; set; }
        public string BISNSS_DPT_CD { get; set; }
        public string BISNSS_USR_CD { get; set; }
        public string SCST_FLG { get; set; }
        public string CSTMR_FLG { get; set; }
        public string SLS_APP_TMG_TYP { get; set; }
        public string SHIP_SLIP_ISSU_FLG { get; set; }
        public string IV_TGT_FLG { get; set; }
        public string CST_CD1 { get; set; }
        public string CST_CD2 { get; set; }
        public string CST_CD3 { get; set; }
        public string CST_CD4 { get; set; }
        public string INVALID_FLG { get; set; }
        public string NOTE { get; set; }
        public Nullable<System.DateTime> INS_TS { get; set; }
        public string INS_USR_ID { get; set; }
        public int UPD_CNTR { get; set; }
        public Nullable<System.DateTime> UPD_TS { get; set; }
        public string UPD_USR_ID { get; set; }
    }
}
