//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CM_RATE_ALL
    {
        public string CURRENCY_CD { get; set; }
        public string BASE_CURRENCY_CD { get; set; }
        public System.DateTime START_TS { get; set; }
        public string EXCHANGE_RATE_TYP { get; set; }
        public string CO_CD { get; set; }
        public decimal BASE_RATE { get; set; }
        public string NOTE { get; set; }
        public System.DateTime END_TS { get; set; }
        public Nullable<System.DateTime> INS_TS { get; set; }
        public string INS_USR_ID { get; set; }
        public int UPD_CNTR { get; set; }
        public Nullable<System.DateTime> UPD_TS { get; set; }
        public string UPD_USR_ID { get; set; }
    }
}
