//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CM_TOKUI_ALL
    {
        public string CST_CD { get; set; }
        public string CO_CD { get; set; }
        public string CST_NM { get; set; }
        public string BISNSS_DPT_CD { get; set; }
        public string BISNSS_USR_CD { get; set; }
        public string ACST_CD { get; set; }
        public string BCST_CD { get; set; }
        public string CRED_CD { get; set; }
        public string SLS_TTL_CD { get; set; }
        public string SLO_ENT_NG_FLG { get; set; }
        public string SCST_SHET_NEC_FLG { get; set; }
        public string SCST_AMT_PRNT_FLG { get; set; }
        public string BILL_SHET_REQ_FLG { get; set; }
        public string SLS_RND_TYP { get; set; }
        public string SLS_CTAX_CD { get; set; }
        public string NEW_SLS_CTAX_CD { get; set; }
        public Nullable<System.DateTime> NEW_SLS_CTAX_CD_ST_DT { get; set; }
        public string CTAX_RND_TYP { get; set; }
        public string CTAX_CALC_TYP { get; set; }
        public string IV_TGT_FLG { get; set; }
        public string BILL_D_OTP_TYP { get; set; }
        public string BILL_D_OTP_ORD_TYP { get; set; }
        public Nullable<short> BILL_CL_DT { get; set; }
        public Nullable<short> BILL_CL_PROCESS_DT { get; set; }
        public Nullable<short> BILL_CL_FIX_DT { get; set; }
        public Nullable<short> BILL_MTH_BASE { get; set; }
        public Nullable<short> RCV_SCHD_MTH { get; set; }
        public Nullable<short> RCV_SCHD_DT { get; set; }
        public Nullable<decimal> CDT_LMT_AMT { get; set; }
        public string INCTRMS_CD { get; set; }
        public string UKEBASHO_CD { get; set; }
        public string PAY_COND_CD { get; set; }
        public string LOC_CD { get; set; }
        public string INVALID_FLG { get; set; }
        public string NOTE { get; set; }
        public Nullable<System.DateTime> INS_TS { get; set; }
        public string INS_USR_ID { get; set; }
        public int UPD_CNTR { get; set; }
        public Nullable<System.DateTime> UPD_TS { get; set; }
        public string UPD_USR_ID { get; set; }
        public string IV_SUM_TYP { get; set; }
        public string SLS_UPRI_TYP { get; set; }
    }
}
