//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HM_TOKUIH_ALL
    {
        public string ITM_CD { get; set; }
        public string CST_CD { get; set; }
        public string CO_CD { get; set; }
        public string CST_ITM_CD { get; set; }
        public string CST_ITM_NM { get; set; }
        public string CST_EXT_ITM_NM { get; set; }
        public string INVALID_FLG { get; set; }
        public string RMRKS { get; set; }
        public Nullable<System.DateTime> INS_TS { get; set; }
        public string INS_USR_CD { get; set; }
        public int UPD_CNTR { get; set; }
        public Nullable<System.DateTime> UPD_TS { get; set; }
        public string UPD_USR_CD { get; set; }
    }
}
