//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<SBS_COMS_COUNTER_NUMBER_ALL> SBS_COMS_COUNTER_NUMBER_ALL { get; set; }
        public DbSet<SBS_HT_JUCHUH_TMP_ALL> SBS_HT_JUCHUH_TMP_ALL { get; set; }
        public DbSet<SBS_HT_JUCHUJ_TMP_ALL> SBS_HT_JUCHUJ_TMP_ALL { get; set; }
        public DbSet<SBS_SM_COMS_FILE_MAP_ALL> SBS_SM_COMS_FILE_MAP_ALL { get; set; }
        public DbSet<CM_COUNTRY_ALL> CM_COUNTRY_ALL { get; set; }
        public DbSet<CM_INCOTERMS_ALL> CM_INCOTERMS_ALL { get; set; }
        public DbSet<CM_ITM_UNIT_ALL> CM_ITM_UNIT_ALL { get; set; }
        public DbSet<HM_TOKUIH_ALL> HM_TOKUIH_ALL { get; set; }
        public DbSet<SC_SYSTEM_ALL> SC_SYSTEM_ALL { get; set; }
        public DbSet<SBS_COMS_USER> SBS_COMS_USER { get; set; }
        public DbSet<SBS_SC_PO_STATUS> SBS_SC_PO_STATUS { get; set; }
        public DbSet<CM_HINMO_ALL> CM_HINMO_ALL { get; set; }
        public DbSet<CM_HINMOI_ALL> CM_HINMOI_ALL { get; set; }
        public DbSet<CM_TOKUI_ALL> CM_TOKUI_ALL { get; set; }
        public DbSet<CM_NOUHIN_ALL> CM_NOUHIN_ALL { get; set; }
        public DbSet<CM_CTAX_ALL> CM_CTAX_ALL { get; set; }
        public DbSet<CM_RATE_ALL> CM_RATE_ALL { get; set; }
        public DbSet<CM_BP_ALL> CM_BP_ALL { get; set; }
        public DbSet<CM_PAYCOND_ALL> CM_PAYCOND_ALL { get; set; }
    
        public virtual int GET_ORD_STS_COUNT(string p_ROLES, string p_CST_CD)
        {
            var p_ROLESParameter = p_ROLES != null ?
                new ObjectParameter("P_ROLES", p_ROLES) :
                new ObjectParameter("P_ROLES", typeof(string));
    
            var p_CST_CDParameter = p_CST_CD != null ?
                new ObjectParameter("P_CST_CD", p_CST_CD) :
                new ObjectParameter("P_CST_CD", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GET_ORD_STS_COUNT", p_ROLESParameter, p_CST_CDParameter);
        }
    }
}
