//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SBS_SM_COMS_FILE_MAP_ALL
    {
        public string CO_CD { get; set; }
        public int SEQ_NO { get; set; }
        public string CST_CD { get; set; }
        public string ACT_CST_CD { get; set; }
        public string CONVERTF { get; set; }
        public string SO_SUCCEEDF { get; set; }
        public string MAIL_SUBJECT { get; set; }
        public Nullable<System.DateTime> INS_TS { get; set; }
        public string INS_USR_ID { get; set; }
        public int UPD_CNTR { get; set; }
        public Nullable<System.DateTime> UPD_TS { get; set; }
        public string UPD_USR_ID { get; set; }
        public string REMARKS { get; set; }
    }
}
