//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SBS_COMS_COUNTER_NUMBER_ALL
    {
        public string CNT_GRP { get; set; }
        public string CO_CD { get; set; }
        public System.DateTime PERIOD { get; set; }
        public string CURR_VALUE { get; set; }
    }
}
