//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SBS_SC_PO_STATUS
    {
        public string STS_ID { get; set; }
        public string STS_NM { get; set; }
        public string CO_CD { get; set; }
    }
}
