//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SBS_COMS_USER
    {
        public string Id { get; set; }
        public string UserName { get; set; }
        public string PasswordHash { get; set; }
        public Nullable<System.DateTimeOffset> LockoutEnd { get; set; }
        public string LockoutEnabled { get; set; }
        public int AccessFailedCount { get; set; }
        public string Company_CD { get; set; }
        public string ISACTIVE { get; set; }
        public string ROLES { get; set; }
        public Nullable<System.DateTime> LAST_LOGIN { get; set; }
        public Nullable<System.DateTime> LAST_LOGOUT { get; set; }
        public string REMARKS { get; set; }
        public Nullable<System.DateTime> EXPIRATION_DT { get; set; }
    }
}
