//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SBS_HT_JUCHUH_TMP_ALL
    {
        public string CO_CD { get; set; }
        public string T_SLO_NO { get; set; }
        public string T_SLO_D_NO { get; set; }
        public string SLO_NO { get; set; }
        public string SLO_D_NO { get; set; }
        public string SET_NO { get; set; }
        public string GRP_NO { get; set; }
        public string SLS_ARRG_TYP { get; set; }
        public string DSH_TYP { get; set; }
        public string ITM_CD { get; set; }
        public string ITM_NM { get; set; }
        public string EXT_ITM_NM { get; set; }
        public string INPT_UNIT_CD { get; set; }
        public decimal INPT_QTY { get; set; }
        public decimal CNV_QTY { get; set; }
        public string UNIT_CD { get; set; }
        public Nullable<System.DateTime> SHIP_RQST_DT { get; set; }
        public Nullable<System.DateTime> RQST_DLV_DT { get; set; }
        public Nullable<System.DateTime> APPRV_DT { get; set; }
        public string APPRV_STS_TYP { get; set; }
        public string APPRV_USR_CD { get; set; }
        public decimal QTY { get; set; }
        public decimal UPRI { get; set; }
        public decimal SPE_DSCNT_UPRI { get; set; }
        public string DSCNT_FLG { get; set; }
        public decimal DSCNT { get; set; }
        public decimal DSCNT_UPRI { get; set; }
        public decimal SLS_AMT { get; set; }
        public decimal XTX_SLS_AMT { get; set; }
        public string CTAX_SPEC_FLG { get; set; }
        public string CTAX_CD { get; set; }
        public decimal CTAX_RATE { get; set; }
        public string CTAX_TYP { get; set; }
        public Nullable<decimal> CTAX_AMT { get; set; }
        public Nullable<decimal> SLS_COST_UPRI { get; set; }
        public string RMRKS { get; set; }
        public string CAN_FLG { get; set; }
        public Nullable<System.DateTime> CAN_DT { get; set; }
        public string CAN_USR_CD { get; set; }
        public string CUR_CD { get; set; }
        public Nullable<decimal> XRATE { get; set; }
        public Nullable<System.DateTime> XRATE_DT { get; set; }
        public string XCNTRCT_FLG { get; set; }
        public string XCNTRCT_NO { get; set; }
        public Nullable<decimal> BCUR_XTX_SLS_AMT { get; set; }
        public string XRATE_TYP { get; set; }
        public string SNO { get; set; }
        public string SUB_SNO { get; set; }
        public Nullable<System.DateTime> INS_TS { get; set; }
        public string INS_USR_CD { get; set; }
        public Nullable<int> UPD_CNTR { get; set; }
        public Nullable<System.DateTime> UPD_TS { get; set; }
        public string UPD_USR_CD { get; set; }
        public Nullable<System.DateTime> RQST_ARVD_DT { get; set; }
        public string H_TYP { get; set; }
    
        public virtual SBS_HT_JUCHUJ_TMP_ALL SBS_HT_JUCHUJ_TMP_ALL { get; set; }
    }
}
