//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SC_SYSTEM_ALL
    {
        public string TYP { get; set; }
        public string CD { get; set; }
        public string CO_CD { get; set; }
        public string NM { get; set; }
        public string LITERAL { get; set; }
        public decimal NMC { get; set; }
        public string XPLA { get; set; }
    }
}
